spring.application.name=KrushiVigyan

# MySQL Connection
spring.datasource.url=jdbc:mysql://localhost:3306/krushi_vigyan
spring.datasource.username=root
spring.datasource.password=060831A

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Server
server.port=8080

# Debug Logs
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.http.converter.json=DEBUG